version: '3.1'
services:
  db:
    image: mysql:5.7
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=travel_express
    - MYSQL_USER=travelExpress
    - MYSQL_PASSWORD=travelExpress
    - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    ports:
    - "8081:80"